apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predictive-maintenance-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: predictive-maintenance.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: predictive-maintenance-api
            port:
              number: 80


