apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: predictive-maintenance

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: predictive-maintenance-api
  managed-by: kustomize


